"""
Pydantic v2 request and response schemas for the VedaGPT API.
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, field_validator


# ── Request ───────────────────────────────────────────────────────────────────


class ChatRequest(BaseModel):
    """Request body for POST /api/v1/chat."""

    question: str = Field(
        ...,
        min_length=1,
        description="The user's question about the indexed scripture.",
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Number of passages to retrieve from the vector store.",
    )

    @field_validator("question")
    @classmethod
    def question_not_blank(cls, v: str) -> str:
        stripped = v.strip()
        if not stripped:
            raise ValueError("Question must not be blank or whitespace only.")
        return stripped


# ── Source / citation ─────────────────────────────────────────────────────────


class SourceCitation(BaseModel):
    """A single source citation built programmatically from Qdrant metadata.

    Citations are NEVER generated by the LLM — they are constructed from the
    metadata attached to each retrieved vector record.
    """

    document_id: str = Field(..., description="Unique verse identifier, e.g. 'gita-2-47'.")
    scripture: str
    chapter: int
    verse: int
    translation: str = Field(default="", description="Retrieved translation text.")
    translator: str = Field(default="", description="Translator name from metadata.")
    edition: str = Field(default="", description="Edition name from metadata.")
    source_reference: str = Field(default="", description="Bibliographic reference from metadata.")
    retrieval_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Cosine similarity score returned by Qdrant.",
    )


# ── Response ──────────────────────────────────────────────────────────────────


class ChatResponse(BaseModel):
    """Response body for POST /api/v1/chat."""

    answer: str = Field(..., description="The grounded explanation.")
    grounded: bool = Field(
        ...,
        description="True when at least one retrieved passage supports the answer.",
    )
    sources: list[SourceCitation] = Field(
        default_factory=list,
        description="Citations derived from retrieved Qdrant records.",
    )
    message: Optional[str] = Field(
        default=None,
        description="Optional informational or error message.",
    )


# ── Health ────────────────────────────────────────────────────────────────────


class HealthResponse(BaseModel):
    """Response body for GET /health."""

    status: str
    service: str
