import { useEffect } from 'react'
import { env } from '@/config/env'
export function AboutPage() {
  useEffect(() => { document.title = 'About -- ' + env.appName }, [])
  return (
    <div className="max-w-2xl mx-auto px-4 sm:px-6 py-12">
      <h1 className="text-2xl font-semibold text-stone-900 dark:text-stone-50 mb-6">About VedaGPT</h1>
      <div className="space-y-6 text-sm text-stone-700 dark:text-stone-300 leading-relaxed">
        <section className="space-y-2">
          <h2 className="font-semibold text-stone-900 dark:text-stone-50">What is VedaGPT?</h2>
          <p>VedaGPT is an educational tool for exploring indexed scripture passages using retrieval-augmented generation (RAG). You ask a question; the system retrieves relevant passages from the indexed corpus and uses a language model to produce an explanation grounded in those passages.</p>
        </section>
        <section className="space-y-2">
          <h2 className="font-semibold text-stone-900 dark:text-stone-50">How does grounding work?</h2>
          <p>Each answer is accompanied by programmatic citations built from the metadata of retrieved vector records. Citations are <strong>never</strong> generated by the AI &mdash; they are extracted from the indexed corpus. If sufficient evidence is not found, the system says so rather than generating an unsupported answer.</p>
        </section>
        <section className="space-y-2">
          <h2 className="font-semibold text-stone-900 dark:text-stone-50">Current corpus</h2>
          <p>{env.isDemoMode ? 'VedaGPT is currently running with limited demonstration data intended for technical evaluation only.' : 'VedaGPT is indexing selected Bhagavad Gita passages.'}</p>
        </section>
        <section className="space-y-2">
          <h2 className="font-semibold text-stone-900 dark:text-stone-50">Important limitations</h2>
          <ul className="list-disc list-inside space-y-1">
            <li>Answers are AI-generated and may contain errors.</li>
            <li>Always verify citations against the referenced edition.</li>
            <li>Different traditions may interpret the same scripture differently.</li>
            <li>VedaGPT is an educational tool, not a religious authority.</li>
            <li>This service does not provide medical, legal, or financial advice.</li>
          </ul>
        </section>
      </div>
    </div>
  )
}
